### PR TITLE
Add fill settings to add prefixes to wrapped lines

### LINKED ISSUE #8: Wrapping with lines after the first indented?
I would really like a wrapping mode where every line after the first line is indented, e.g. something like
```
"This is a really long line" -->  "This is a\n  really\n  long line."
```
Would you be open to a PR implementing this functionality?  What do you think would be the best way to go about it?  Perhaps adding a field to the `WrapSettings` of type `Maybe Int` (or just `Int`)?  I'm happy to take a crack at implementing it but wanted to make sure we agree on the best approach first.

### PR DESCRIPTION
**Pull request by byorgey**
Closes #8.

I'm pretty happy with how this turned out in the end.  It's a lot of code in an absolute sense, but it's mostly pretty modular.  The only existing function I had to make a bunch of changes to was `wrapLine`, but I think I was able to change it in a way that didn't make it much more complex than it already was.  Happy to address any issues or suggestions you might have.

### CODE REVIEW

**Comment by jtdaugherty** [comment]
This looks great to me. Thank you for your work on this, and thank you for also adding tests!

**Comment by byorgey** [comment]
You're welcome!  And if you would be so kind as to release to Hackage when you get a chance, that would be great.  Hopefully it should be possible to use the new version of `word-wrap` with existing versions of `brick` without having to make a new release of `brick` as well?

**Comment by jtdaugherty** [comment]
This change is now released in 0.5.

**Comment by jtdaugherty** [comment]
(And yeah, `brick` has no upper bound on `word-wrap` and doesn't depend on knowing what fields `WrapSettings` has.)

**Pull request merged**
